modLoader="javafml"
loaderVersion="[0,)"
license="All Rights Reserved"

[[mods]]
modId="firstmodblueabstraction"
version="0.0.1"
displayName="First Mod"
description="(blue)->{Abstraction();};'s first mod."
authors="Blue Abstraction"

[[dependencies.firstmodblueabstraction]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.firstmodblueabstraction]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
